<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('account_active_requests', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id');
            $table->string('status', 100)->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('activities', function (Blueprint $table): void {
            $table->integer('activity_id')->autoIncrement();
            $table->string('activity_type', 255)->nullable();
            $table->integer('title')->nullable();
            $table->integer('icon')->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('addons', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->string('title', 255)->nullable();
            $table->integer('parent_id')->nullable();
            $table->string('features', 255)->nullable();
            $table->float('version')->nullable();
            $table->string('unique_identifier', 255)->nullable();
            $table->integer('status')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });
        Schema::create('albums', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('page_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->string('title', 255)->nullable();
            $table->string('sub_title', 500)->nullable();
            $table->string('thumbnail', 255)->nullable();
            $table->string('privacy', 255)->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('album_images', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('album_id');
            $table->integer('user_id');
            $table->integer('page_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->text('image')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('batchs', function (Blueprint $table): void {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->integer('user_id')->nullable();
            $table->string('title', 255)->nullable();
            $table->longText('description')->nullable();
            $table->string('icon', 255)->nullable();
            $table->integer('status')->nullable();
            $table->timestamp('start_date')->useCurrent()->nullable();
            $table->timestamp('end_date')->useCurrent()->nullable();
            $table->timestamp('created_at')->useCurrent()->nullable();
            $table->timestamp('updated_at')->useCurrent()->nullable();
        });
        Schema::create('block_users', function (Blueprint $table): void {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->integer('user_id')->nullable();
            $table->integer('block_user')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
        });
        Schema::create('blogcategories', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->text('name');
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('blogs', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('category_id')->nullable();
            $table->string('title', 255)->nullable();
            $table->longText('description')->nullable();
            $table->string('thumbnail', 255)->nullable();
            $table->string('banner', 255)->nullable();
            $table->string('status', 100)->nullable();
            $table->text('tag')->nullable();
            $table->text('view')->nullable();
            $table->string('created_at', 100);
            $table->string('updated_at', 100);
        });
        Schema::create('brands', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->text('name')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('categories', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->text('name')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('chats', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('message_thrade')->nullable();
            $table->integer('message_thread_id')->nullable();
            $table->integer('reciver_id')->nullable();
            $table->integer('receiver_id')->nullable();
            $table->integer('sender_id')->nullable();
            $table->text('message')->nullable();
            $table->boolean('thumbsup')->default(0);
            $table->text('file')->nullable();
            $table->text('react')->nullable();
            $table->integer('reply_id')->nullable();
            $table->text('chatcenter')->nullable();
            $table->text('chat_center')->nullable();
            $table->boolean('read_status')->default(0);
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
            $table->index('message_thread_id', 'chats_message_thread_id_idx');
            $table->index('receiver_id', 'chats_receiver_id_idx');
            $table->index(['sender_id', 'receiver_id'], 'chats_sender_receiver_clean_idx');
        });
        Schema::create('comments', function (Blueprint $table): void {
            $table->integer('comment_id')->autoIncrement();
            $table->integer('parent_id')->default(0);
            $table->integer('user_id')->nullable();
            $table->string('is_type', 100)->nullable();
            $table->integer('id_of_type')->nullable();
            $table->longText('description')->nullable();
            $table->longText('user_reacts')->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('currencies', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->string('name', 255)->nullable();
            $table->string('code', 255)->nullable();
            $table->string('symbol', 255)->nullable();
            $table->integer('paypal_supported')->nullable();
            $table->integer('stripe_supported')->nullable();
        });
        Schema::create('events', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->string('publisher', 100)->nullable();
            $table->integer('publisher_id')->nullable();
            $table->string('title', 255)->nullable();
            $table->longText('description')->nullable();
            $table->string('event_date', 100)->nullable();
            $table->string('event_time', 255)->nullable();
            $table->text('location')->nullable();
            $table->longText('going_users_id')->nullable();
            $table->longText('interested_users_id')->nullable();
            $table->string('thumbnail', 255)->nullable();
            $table->string('banner', 255)->nullable();
            $table->string('privacy', 50)->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('failed_jobs', function (Blueprint $table): void {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('uuid', 255)->nullable();
            $table->text('connection')->nullable();
            $table->text('queue')->nullable();
            $table->longText('payload')->nullable();
            $table->longText('exception')->nullable();
            $table->timestamp('failed_at')->useCurrent();
            $table->unique('uuid', 'failed_jobs_uuid_unique');
        });
        Schema::create('feeling_and_activities', function (Blueprint $table): void {
            $table->integer('feeling_and_activity_id')->autoIncrement();
            $table->string('type', 255);
            $table->string('title', 255);
            $table->string('icon', 255);
            $table->string('created_at', 100);
            $table->string('updated_at', 100);
        });
        Schema::create('followers', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('follow_id')->nullable();
            $table->integer('page_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('friendships', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('requester')->nullable();
            $table->integer('accepter')->nullable();
            $table->integer('importance')->nullable();
            $table->integer('is_accepted')->nullable();
            $table->string('accepted_at', 100)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('groups', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->text('user_id')->nullable();
            $table->string('title', 255)->nullable();
            $table->string('subtitle', 300)->nullable();
            $table->string('privacy', 255)->nullable();
            $table->string('location', 255)->nullable();
            $table->string('group_type', 300)->nullable();
            $table->string('logo', 255)->nullable();
            $table->string('banner', 255)->nullable();
            $table->longText('about')->nullable();
            $table->string('status', 100)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('group_members', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->string('is_accepted', 10)->nullable();
            $table->string('role', 100)->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('invites', function (Blueprint $table): void {
            $table->bigInteger('id')->autoIncrement();
            $table->integer('invite_sender_id')->nullable();
            $table->integer('invite_reciver_id')->nullable();
            $table->integer('is_accepted')->default(0);
            $table->integer('event_id')->nullable();
            $table->integer('page_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->integer('fundraiser_id')->nullable();
            $table->integer('post_id')->nullable();
            $table->timestamp('created_at')->useCurrent()->useCurrentOnUpdate();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('languages', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->string('name', 50)->nullable();
            $table->string('phrase', 300)->nullable();
            $table->string('translated', 300)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('live_streamings', function (Blueprint $table): void {
            $table->integer('streaming_id')->autoIncrement();
            $table->string('publisher', 255)->nullable();
            $table->integer('publisher_id')->nullable();
            $table->integer('user_id')->nullable();
            $table->longText('details')->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('marketplaces', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->string('title', 255)->nullable();
            $table->integer('currency_id')->nullable();
            $table->string('price', 15)->nullable();
            $table->string('location', 255)->nullable();
            $table->text('category')->nullable();
            $table->string('status', 250)->nullable();
            $table->text('condition')->nullable();
            $table->string('brand', 250)->nullable();
            $table->string('buy_link', 300)->nullable();
            $table->text('description')->nullable();
            $table->string('image', 250)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('media_files', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('post_id')->nullable();
            $table->integer('story_id')->nullable();
            $table->integer('album_id')->nullable();
            $table->integer('product_id')->nullable();
            $table->integer('page_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->integer('chat_id')->nullable();
            $table->integer('album_image_id')->nullable();
            $table->string('file_name', 255)->nullable();
            $table->string('file_type', 255)->nullable();
            $table->string('privacy', 200)->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('message_thrades', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('reciver_id')->nullable();
            $table->integer('receiver_id')->nullable();
            $table->integer('sender_id')->nullable();
            $table->text('chatcenter')->nullable();
            $table->text('chat_center')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
            $table->index('receiver_id', 'message_thrades_receiver_id_idx');
            $table->index(['sender_id', 'receiver_id'], 'message_thrades_sender_receiver_clean_idx');
        });
        Schema::create('notifications', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('sender_user_id')->nullable();
            $table->integer('reciver_user_id')->nullable();
            $table->string('type', 255)->nullable();
            $table->integer('event_id')->nullable();
            $table->integer('page_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->integer('fundraiser_id')->nullable();
            $table->integer('status')->default(0)->nullable();
            $table->integer('view')->default(0)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('pagecategories', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->string('name', 255)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('pages', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->string('title', 255)->nullable();
            $table->string('subtitle', 300)->nullable();
            $table->string('page_type', 300)->nullable();
            $table->integer('category_id')->nullable();
            $table->text('logo')->nullable();
            $table->string('coverphoto', 255)->nullable();
            $table->longText('description')->nullable();
            $table->text('job')->nullable();
            $table->text('lifestyle')->nullable();
            $table->text('location')->nullable();
            $table->string('status', 100)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('page_likes', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('page_id')->nullable();
            $table->string('role', 100)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('password_resets', function (Blueprint $table): void {
            $table->string('email', 255);
            $table->string('token', 255);
            $table->timestamp('created_at')->nullable();
            $table->index('email', 'password_resets_email_index');
        });
        Schema::create('payment_gateways', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->string('identifier', 255)->nullable();
            $table->string('currency', 100)->nullable();
            $table->string('title', 255)->nullable();
            $table->text('description')->nullable();
            $table->text('keys')->nullable();
            $table->string('model_name', 255)->nullable();
            $table->integer('test_mode')->nullable();
            $table->integer('status')->nullable();
            $table->integer('is_addon')->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('payment_histories', function (Blueprint $table): void {
            $table->bigInteger('id')->autoIncrement();
            $table->string('item_type', 255)->nullable();
            $table->bigInteger('item_id')->nullable();
            $table->bigInteger('user_id')->nullable();
            $table->double('amount')->nullable();
            $table->string('currency', 100)->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
            $table->string('identifier', 255)->nullable();
            $table->longText('transaction_keys')->nullable();
            $table->string('order_id', 255)->nullable();
            $table->string('transaction_id', 255)->nullable();
            $table->tinyInteger('status')->unsigned()->nullable();
            $table->index('order_id', 'payment_histories_order_id_idx');
        });
        Schema::create('personal_access_tokens', function (Blueprint $table): void {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('tokenable_type', 255);
            $table->bigInteger('tokenable_id')->unsigned();
            $table->string('name', 255);
            $table->string('token', 64);
            $table->text('abilities')->nullable();
            $table->timestamp('last_used_at')->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->string('expires_at', 255)->nullable();
            $table->unique('token', 'personal_access_tokens_token_unique');
            $table->index(['tokenable_type', 'tokenable_id'], 'personal_access_tokens_tokenable_type_tokenable_id_index');
        });
        Schema::create('posts', function (Blueprint $table): void {
            $table->integer('post_id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->string('publisher', 100)->nullable();
            $table->integer('publisher_id')->nullable();
            $table->string('post_type', 255)->nullable();
            $table->string('privacy', 100)->nullable();
            $table->longText('tagged_user_ids')->nullable();
            $table->integer('activity_id')->nullable();
            $table->string('location', 300)->nullable();
            $table->longText('description')->nullable();
            $table->string('status', 100)->nullable();
            $table->boolean('report_status')->default(0);
            $table->longText('user_reacts')->nullable();
            $table->text('shared_user')->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
            $table->timestamp('posted_on')->useCurrent();
            $table->string('hashtag', 255)->nullable();
            $table->string('album_image_id', 255)->nullable();
            $table->string('mobile_app_image', 255)->nullable();
        });
        Schema::create('post_shares', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('post_id')->nullable();
            $table->text('shared_on')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('reports', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('post_id')->nullable();
            $table->text('report')->nullable();
            $table->boolean('status')->default(0);
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('saved_products', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('product_id')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('saveforlaters', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->integer('video_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->integer('post_id')->nullable();
            $table->integer('marketplace_id')->nullable();
            $table->integer('event_id')->nullable();
            $table->integer('blog_id')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('settings', function (Blueprint $table): void {
            $table->integer('setting_id')->autoIncrement();
            $table->string('type', 255)->nullable();
            $table->longText('description')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('shares', function (Blueprint $table): void {
            $table->bigInteger('id')->autoIncrement();
            $table->text('share_user_id')->nullable();
            $table->integer('event_id')->nullable();
            $table->integer('page_id')->nullable();
            $table->integer('group_id')->nullable();
            $table->text('url')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('sponsors', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id');
            $table->text('name')->nullable();
            $table->text('description')->nullable();
            $table->text('ext_url')->nullable();
            $table->string('image', 255)->nullable();
            $table->double('paid_amount')->nullable();
            $table->integer('status')->nullable();
            $table->timestamp('start_date')->useCurrent()->nullable();
            $table->timestamp('end_date')->useCurrent()->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        Schema::create('stories', function (Blueprint $table): void {
            $table->integer('story_id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->string('publisher', 100)->nullable();
            $table->integer('publisher_id')->nullable();
            $table->string('privacy', 255)->nullable();
            $table->string('content_type', 255)->nullable();
            $table->longText('media_files')->nullable();
            $table->longText('description')->nullable();
            $table->string('status', 100)->nullable();
            $table->string('created_at', 100)->nullable();
            $table->string('updated_at', 100)->nullable();
        });
        Schema::create('users', function (Blueprint $table): void {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->string('user_role', 255)->nullable();
            $table->string('username', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->string('password', 255)->nullable();
            $table->string('name', 255)->nullable();
            $table->string('nickname', 255)->nullable();
            $table->longText('friends')->nullable();
            $table->longText('followers')->nullable();
            $table->string('gender', 100)->nullable();
            $table->string('studied_at', 300)->nullable();
            $table->string('address', 300)->nullable();
            $table->string('profession', 300)->nullable();
            $table->string('job', 300)->nullable();
            $table->string('marital_status', 255)->nullable();
            $table->string('phone', 100)->nullable();
            $table->string('date_of_birth', 100)->nullable();
            $table->longText('about')->nullable();
            $table->longText('save_post')->nullable();
            $table->string('photo', 255)->nullable();
            $table->string('cover_photo', 255)->nullable();
            $table->string('status', 100)->nullable();
            $table->timestamp('lastActive')->nullable();
            $table->string('timezone', 255)->nullable();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('remember_token', 100)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->longText('payment_settings')->nullable();
            $table->string('profile_status', 100)->nullable();
            $table->unique('email', 'users_email_unique');
        });
        Schema::create('videos', function (Blueprint $table): void {
            $table->integer('id')->autoIncrement();
            $table->integer('user_id')->nullable();
            $table->string('title', 255)->nullable();
            $table->text('category')->nullable();
            $table->text('privacy')->nullable();
            $table->text('file')->nullable();
            $table->text('view')->nullable();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
            $table->string('mobile_app_image', 255)->nullable();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('videos');
        Schema::dropIfExists('users');
        Schema::dropIfExists('stories');
        Schema::dropIfExists('sponsors');
        Schema::dropIfExists('shares');
        Schema::dropIfExists('settings');
        Schema::dropIfExists('saveforlaters');
        Schema::dropIfExists('saved_products');
        Schema::dropIfExists('reports');
        Schema::dropIfExists('post_shares');
        Schema::dropIfExists('posts');
        Schema::dropIfExists('personal_access_tokens');
        Schema::dropIfExists('payment_histories');
        Schema::dropIfExists('payment_gateways');
        Schema::dropIfExists('password_resets');
        Schema::dropIfExists('page_likes');
        Schema::dropIfExists('pages');
        Schema::dropIfExists('pagecategories');
        Schema::dropIfExists('notifications');
        Schema::dropIfExists('message_thrades');
        Schema::dropIfExists('media_files');
        Schema::dropIfExists('marketplaces');
        Schema::dropIfExists('live_streamings');
        Schema::dropIfExists('languages');
        Schema::dropIfExists('invites');
        Schema::dropIfExists('group_members');
        Schema::dropIfExists('groups');
        Schema::dropIfExists('friendships');
        Schema::dropIfExists('followers');
        Schema::dropIfExists('feeling_and_activities');
        Schema::dropIfExists('failed_jobs');
        Schema::dropIfExists('events');
        Schema::dropIfExists('currencies');
        Schema::dropIfExists('comments');
        Schema::dropIfExists('chats');
        Schema::dropIfExists('categories');
        Schema::dropIfExists('brands');
        Schema::dropIfExists('blogs');
        Schema::dropIfExists('blogcategories');
        Schema::dropIfExists('block_users');
        Schema::dropIfExists('batchs');
        Schema::dropIfExists('album_images');
        Schema::dropIfExists('albums');
        Schema::dropIfExists('addons');
        Schema::dropIfExists('activities');
        Schema::dropIfExists('account_active_requests');
    }
};
