<?php

namespace App\Support\Files;

use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Image;
use InvalidArgumentException;
use RuntimeException;

class FileUploader
{
    /**
     * @var list<string>
     */
    private const EXECUTABLE_EXTENSIONS = [
        'bat',
        'cgi',
        'cmd',
        'com',
        'exe',
        'js',
        'msi',
        'phtml',
        'phar',
        'php',
        'pl',
        'py',
        'sh',
    ];

    public static function upload($uploaded_file, $upload_to, $width = null, $height = null, $optimized_width = 250, $optimized_height = null)
    {
        if (! $uploaded_file) {
            return;
        }

        if (! $uploaded_file instanceof UploadedFile) {
            throw new InvalidArgumentException('Uploaded file must be an instance of UploadedFile.');
        }

        self::assertAllowedUploadedFile($uploaded_file);

        $s3_keys = get_settings('amazon_s3', 'object');
        if ((int) ($s3_keys->active ?? 0) !== 1) {
            return self::uploadToPublicDisk(
                $uploaded_file,
                $upload_to,
                $width,
                $height,
                $optimized_width,
                $optimized_height,
            );
        }

        // upload to amazon s3
        ini_set('max_execution_time', '600');
        config(['filesystems.disks.s3.key' => $s3_keys->AWS_ACCESS_KEY_ID]);
        config(['filesystems.disks.s3.secret' => $s3_keys->AWS_SECRET_ACCESS_KEY]);
        config(['filesystems.disks.s3.region' => $s3_keys->AWS_DEFAULT_REGION]);
        config(['filesystems.disks.s3.bucket' => $s3_keys->AWS_BUCKET]);

        // social-files this directory automatically created on S3 server, the file upload in this folder
        // The file name generated by laravel s3 package
        $s3_file_path = Storage::disk('s3')->put('social-files', $uploaded_file, 'public');
        $s3_file_path = Storage::disk('s3')->url($s3_file_path);

        return $s3_file_path;
    }

    private static function uploadToPublicDisk(
        UploadedFile $uploadedFile,
        string $uploadTo,
        ?int $width,
        ?int $height,
        int $optimizedWidth,
        ?int $optimizedHeight,
    ): string {
        [$directory, $fileName] = self::publicDiskTarget($uploadedFile, $uploadTo);

        Storage::disk('public')->makeDirectory($directory);

        if ($width === null) {
            self::putUploadedFile($uploadedFile, $directory.'/'.$fileName);

            return $fileName;
        }

        self::putResizedImage($uploadedFile, $directory.'/'.$fileName, $width, $height);

        $optimizedDirectory = $directory.'/optimized';
        if (self::optimizedDirectoryExists($optimizedDirectory)) {
            Storage::disk('public')->makeDirectory($optimizedDirectory);
            self::putResizedImage($uploadedFile, $optimizedDirectory.'/'.$fileName, $optimizedWidth, $optimizedHeight);
        }

        return $fileName;
    }

    /**
     * @return array{0: string, 1: string}
     */
    private static function publicDiskTarget(UploadedFile $uploadedFile, string $uploadTo): array
    {
        $target = trim(str_replace('\\', '/', $uploadTo), '/');
        $prefix = 'public/storage/';

        if (! str_starts_with($target, $prefix)) {
            throw new InvalidArgumentException('Local uploads must target the public storage disk.');
        }

        $relativeTarget = trim(substr($target, strlen($prefix)), '/');
        self::assertSafeRelativePath($relativeTarget);

        $fileName = self::looksLikeFileTarget($relativeTarget)
            ? basename($relativeTarget)
            : self::generatedFileName($uploadedFile);
        $directory = self::looksLikeFileTarget($relativeTarget)
            ? dirname($relativeTarget)
            : $relativeTarget;

        if ($directory === '.') {
            $directory = '';
        }

        self::assertSafeRelativePath($directory);
        self::assertSafeFileName($fileName);

        return [$directory, $fileName];
    }

    private static function putUploadedFile(UploadedFile $uploadedFile, string $path): void
    {
        $contents = file_get_contents($uploadedFile->getPathname());
        if ($contents === false) {
            throw new RuntimeException('Unable to read uploaded file.');
        }

        if (Storage::disk('public')->put($path, $contents, ['visibility' => 'public']) === false) {
            throw new RuntimeException('Unable to write uploaded file.');
        }
    }

    private static function putResizedImage(UploadedFile $uploadedFile, string $path, int $width, ?int $height): void
    {
        $temporaryPath = tempnam(sys_get_temp_dir(), 'sociopro-upload-');
        if ($temporaryPath === false) {
            throw new RuntimeException('Unable to create temporary image file.');
        }

        try {
            Image::make($uploadedFile->path())->orientate()->resize($width, $height, function ($constraint) {
                $constraint->upsize();
                $constraint->aspectRatio();
            })->save($temporaryPath);

            $contents = file_get_contents($temporaryPath);
            if ($contents === false) {
                throw new RuntimeException('Unable to read optimized image.');
            }

            if (Storage::disk('public')->put($path, $contents, ['visibility' => 'public']) === false) {
                throw new RuntimeException('Unable to write optimized image.');
            }
        } finally {
            @unlink($temporaryPath);
        }
    }

    private static function optimizedDirectoryExists(string $directory): bool
    {
        return Storage::disk('public')->directoryExists($directory)
            || is_dir(public_path('storage/'.$directory));
    }

    private static function looksLikeFileTarget(string $relativeTarget): bool
    {
        return pathinfo($relativeTarget, PATHINFO_EXTENSION) !== '';
    }

    private static function generatedFileName(UploadedFile $uploadedFile): string
    {
        $extension = self::safeExtension($uploadedFile);
        if ($extension === '') {
            throw new InvalidArgumentException('Uploaded file extension could not be detected.');
        }

        return time().'-'.random(30).'.'.$extension;
    }

    private static function assertSafeRelativePath(string $path): void
    {
        if ($path === '' || str_contains($path, "\0")) {
            throw new InvalidArgumentException('Upload path is invalid.');
        }

        foreach (explode('/', $path) as $segment) {
            if ($segment === '' || $segment === '.' || $segment === '..') {
                throw new InvalidArgumentException('Upload path is invalid.');
            }
        }
    }

    private static function assertSafeFileName(string $fileName): void
    {
        if (! preg_match('/\A[A-Za-z0-9._-]+\z/', $fileName) || str_starts_with($fileName, '.')) {
            throw new InvalidArgumentException('Upload filename is invalid.');
        }

        $extension = strtolower((string) pathinfo($fileName, PATHINFO_EXTENSION));
        if (in_array($extension, self::EXECUTABLE_EXTENSIONS, true)) {
            throw new InvalidArgumentException('Executable uploads are not allowed.');
        }
    }

    private static function assertAllowedUploadedFile(UploadedFile $uploadedFile): void
    {
        $originalName = $uploadedFile->getClientOriginalName();
        if (str_contains($originalName, "\0")) {
            throw new InvalidArgumentException('Uploaded filename is invalid.');
        }

        $extension = self::safeExtension($uploadedFile);
        if (in_array($extension, self::EXECUTABLE_EXTENSIONS, true)) {
            throw new InvalidArgumentException('Executable uploads are not allowed.');
        }
    }

    private static function safeExtension(UploadedFile $uploadedFile): string
    {
        return strtolower((string) ($uploadedFile->extension() ?: $uploadedFile->getClientOriginalExtension()));
    }
}
